<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify_verificationCode</name>
   <tag></tag>
   <elementGuidId>87f11f75-144a-47fd-ad6c-762b0345897a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verificationCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#verificationCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>686ad603-6f47-49e4-ba52-a09b31d529a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verificationCode</value>
      <webElementGuid>02913b2a-e439-4290-91ca-65217c29ddb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Verification Code</value>
      <webElementGuid>7b1be75e-5584-448a-9f0b-42ca679f8132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da745cb5-8f96-496f-abff-b5afed006c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiInputBase-input base-MuiInput-input</value>
      <webElementGuid>d53d4a08-f770-46f9-994a-77caf2639708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verificationCode&quot;)</value>
      <webElementGuid>3573d661-6c71-4bb0-832f-b1b9ee2ff6e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verificationCode']</value>
      <webElementGuid>00283a90-edd5-4bc4-9634-37b40f3b22ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div[2]/div/div[2]/form/div[2]/div/div/input</value>
      <webElementGuid>42d60b26-afc2-49a4-b590-0965282d47ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>d60dcb76-eee7-4695-aad2-3d954ce07012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'verificationCode' and @placeholder = 'Verification Code' and @type = 'text']</value>
      <webElementGuid>2912b5bd-e248-4c6f-820d-12aa72422de0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
