<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify_verificationCode</name>
   <tag></tag>
   <elementGuidId>87f11f75-144a-47fd-ad6c-762b0345897a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#verificationCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='verificationCode']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'verificationCode' and @placeholder = 'Verification Code' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9afabf2-481a-4ed6-a1ae-6daa519a36f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>verificationCode</value>
      <webElementGuid>4ceecde2-39cd-42dc-bae3-92ed093c1154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Verification Code</value>
      <webElementGuid>05a094e2-577d-4419-a6c8-7749f7370ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f869978-c728-4041-8221-26abd6210085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiInputBase-input base-MuiInput-input</value>
      <webElementGuid>6551599c-7de5-45d1-9f1a-b1772ac8cef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;verificationCode&quot;)</value>
      <webElementGuid>2bfbe244-ef56-45ed-9123-f3ed094e5049</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='verificationCode']</value>
      <webElementGuid>a58f285a-fb72-4324-a025-5472039ab660</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
