<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_What can you do in Change or Cancel Request List</name>
   <tag></tag>
   <elementGuidId>e2c136a6-2f57-4958-9137-ee86372ba043</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id = 'oneTimePopUpHeader' and (text() = 'What can you do in Change or Cancel Request List?' or . = 'What can you do in Change or Cancel Request List?')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#oneTimePopUpHeader</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>bf16c5ed-7817-4d1b-94f4-ab2ab7850c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>oneTimePopUpHeader</value>
      <webElementGuid>18777548-f96c-4710-b0a9-58ca5d1c2983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>What can you do in Change or Cancel Request List?</value>
      <webElementGuid>efdb7131-fa2e-4097-ac69-e61929b917fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;oneTimePopUpHeader&quot;)</value>
      <webElementGuid>73f6b5b4-be2c-40df-a688-bb8d5d18d388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='oneTimePopUpHeader']</value>
      <webElementGuid>7b6882dd-0050-4de5-964c-b290b7f56edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/h1</value>
      <webElementGuid>7d6e6b2e-8822-4d91-9178-3e515adb1e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/following::h1[1]</value>
      <webElementGuid>598ad9e0-33c8-4c86-9326-813d34fe3e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECOMMENDATIONS'])[4]/following::h1[1]</value>
      <webElementGuid>caa0d6b5-b9a7-42a9-93d5-4f3238b1877e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::h1[1]</value>
      <webElementGuid>7dff02db-f232-4dad-9a03-302763fb5289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/preceding::h1[1]</value>
      <webElementGuid>5296bace-6621-42c6-afe9-05aa879f2b28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='What can you do in Change or Cancel Request List?']/parent::*</value>
      <webElementGuid>fd9f3fd2-5f34-483d-83ba-6473959699b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>72f374a2-f658-455d-95fb-5037319d8511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'oneTimePopUpHeader' and (text() = 'What can you do in Change or Cancel Request List?' or . = 'What can you do in Change or Cancel Request List?')]</value>
      <webElementGuid>f7755593-fdb8-45d8-96c1-57d92c0ad746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
