<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Outbound Monitoring List</name>
   <tag></tag>
   <elementGuidId>88904b61-e7df-4af0-90d9-6316a12e349e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[(text() = 'Outbound Monitoring List' or . = 'Outbound Monitoring List')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d4f92d03-a5ee-4665-b723-0819b5b3c0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiButtonBase-root base-MuiListItem-root base-MuiMenuItem-root base-base65 base-MuiMenuItem-gutters base-MuiListItem-gutters base-MuiListItem-button</value>
      <webElementGuid>38aa341b-1f14-49f8-8c77-51a8dedb5b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>08245734-88aa-4ba9-9254-51356073d546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>85d936a3-b4ec-4e9d-8c2b-1476fded0bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6a47a737-58bb-477a-9ff9-1e001ef5f7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outbound Monitoring List</value>
      <webElementGuid>b93a41f3-218b-4dc8-ad66-c8a25925082a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;base-base46&quot;]/div[@class=&quot;base-MuiPaper-root base-base47 base-MuiPaper-elevation1 base-MuiPaper-rounded&quot;]/div[@class=&quot;base-base50&quot;]/ul[@class=&quot;base-MuiList-root base-base63 base-MuiList-padding&quot;]/a[2]/li[@class=&quot;base-MuiButtonBase-root base-MuiListItem-root base-MuiMenuItem-root base-base65 base-MuiMenuItem-gutters base-MuiListItem-gutters base-MuiListItem-button&quot;]</value>
      <webElementGuid>046c9453-1508-48bb-a68e-e38e6620ebf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistics'])[2]/following::li[3]</value>
      <webElementGuid>58114ea5-7f01-485a-9fcc-32dddc1c51c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECOMMENDATIONS'])[5]/following::li[3]</value>
      <webElementGuid>95f3e859-8c52-4260-9e1f-5fd2a32fcd45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please rate your experience of our system on below aspects: Aesthetic'])[1]/preceding::li[7]</value>
      <webElementGuid>49ec456a-9a5e-4eba-8260-be4dba04b906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strongly disagree'])[1]/preceding::li[7]</value>
      <webElementGuid>62169341-19fd-4098-bb0a-26a63d8bfdc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/li</value>
      <webElementGuid>c0981269-e89b-4d09-8867-449b85306bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Outbound Monitoring List' or . = 'Outbound Monitoring List')]</value>
      <webElementGuid>99c671e1-231e-4f45-b175-9c7b8b14bd8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
