<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__inboundTime 1</name>
   <tag></tag>
   <elementGuidId>e39e0c6e-ed6d-4ef0-b03c-f095fdda0661</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='inboundTime']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;inboundTime&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8096c512-a34f-4b08-a6fc-547cd494b52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ca2e82f7-25a4-4da2-99a9-c9933a9754ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inboundTime</value>
      <webElementGuid>013ab545-89cd-4545-934a-7493ae2ca5f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ee06ce4c-2daf-44f7-8ec4-c12bae3d6d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>2618afd9-b3db-4c5c-b940-da7f24328af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;lcbm-MuiDialog-root&quot;]/div[@class=&quot;lcbm-MuiDialog-container lcbm-MuiDialog-scrollPaper&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiDialog-paper lcbm-lcbm586 lcbm-MuiDialog-paperScrollPaper lcbm-MuiDialog-paperWidthSm lcbm-MuiDialog-paperFullWidth lcbm-MuiPaper-elevation24 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiDialogContent-root&quot;]/form[@class=&quot;lcbm-lcbm591 lcbm-lcbm592&quot;]/div[@class=&quot;lcbm-lcbm593 lcbm-lcbm618&quot;]/div[@class=&quot;lcbm-lcbm595&quot;]/div[@class=&quot;lcbm-lcbm602&quot;]/div[@class=&quot;lcbm-lcbm608&quot;]/div[@class=&quot;lcbm-lcbm597&quot;]/div[@class=&quot;lcbm-lcbm619&quot;]/div[@class=&quot;lcbm-MuiFormControl-root lcbm-MuiTextField-root&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused lcbm-MuiInputBase-formControl lcbm-MuiInput-formControl&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>2ed5fb1e-72fa-49b3-a581-862afa1503bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='inboundTime']</value>
      <webElementGuid>517dc283-1f04-4266-8b47-5ccf2f2f1faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>6aed30a7-4226-4045-85e6-c40058120ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'inboundTime' and @type = 'text']</value>
      <webElementGuid>111650f1-8042-451c-b989-c18e4410840c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
