<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__inboundDate</name>
   <tag></tag>
   <elementGuidId>2e92c9e5-5e1c-4b17-a9a6-56bb624bedf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='inboundDate']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;inboundDate&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'inboundDate' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>989d4585-4e79-4eb4-8195-8856efbc68dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cd867a45-3475-40df-a755-61047016fa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>inboundDate</value>
      <webElementGuid>0f061495-2546-4aaa-a345-0b10cfe9b817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>451cbeee-d440-4bef-b0bb-27faed090d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>e0f18e9b-ace5-4c64-82ce-b50ad23681ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;lcbm-MuiDialog-root&quot;]/div[@class=&quot;lcbm-MuiDialog-container lcbm-MuiDialog-scrollPaper&quot;]/div[@class=&quot;lcbm-MuiPaper-root lcbm-MuiDialog-paper lcbm-lcbm893 lcbm-MuiDialog-paperScrollPaper lcbm-MuiDialog-paperWidthSm lcbm-MuiDialog-paperFullWidth lcbm-MuiPaper-elevation24 lcbm-MuiPaper-rounded&quot;]/div[@class=&quot;lcbm-MuiDialogContent-root&quot;]/form[@class=&quot;lcbm-lcbm1072 lcbm-lcbm1073&quot;]/div[@class=&quot;lcbm-lcbm1074 lcbm-lcbm1096&quot;]/div[@class=&quot;lcbm-lcbm1076&quot;]/div[@class=&quot;lcbm-lcbm1083&quot;]/div[@class=&quot;lcbm-lcbm1089 lcbm-lcbm1093&quot;]/div[@class=&quot;lcbm-lcbm1078&quot;]/div[@class=&quot;lcbm-lcbm1097&quot;]/div[@class=&quot;lcbm-MuiFormControl-root lcbm-MuiTextField-root&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused lcbm-MuiInputBase-formControl lcbm-MuiInput-formControl&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>6a94a3fe-232c-4f30-b8c8-a4473dd8be82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='inboundDate']</value>
      <webElementGuid>249ff5c0-65c3-49fb-904f-6fbea7c5668a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/input</value>
      <webElementGuid>01ece03a-ea81-4db7-9bd7-4ba70022fcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'inboundDate' and @type = 'text']</value>
      <webElementGuid>304ba983-9912-4063-8441-8af4e13265c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
