<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logistics</name>
   <tag></tag>
   <elementGuidId>ee340aea-9702-4fdb-b3c5-f01aa1ff61b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Logistics' or . = 'Logistics')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.base-MuiButtonBase-root.base-MuiButton-root.base-MuiButton-text.base-base58.base-base59 > span.base-MuiButton-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58459174-2167-4ccd-9a1f-3af2f747de1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiButton-label</value>
      <webElementGuid>e9837f96-0f1b-447d-8e48-bee7f3287016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logistics</value>
      <webElementGuid>733913a0-4002-42ea-8be6-93b01bcdf58a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base42&quot;]/div[@class=&quot;base-base43&quot;]/div[@class=&quot;base-base44&quot;]/div[@class=&quot;base-base46&quot;]/nav[@class=&quot;base-base53&quot;]/div[@class=&quot;base-base54&quot;]/div[@class=&quot;base-base55&quot;]/button[@class=&quot;base-MuiButtonBase-root base-MuiButton-root base-MuiButton-text base-base58 base-base59&quot;]/span[@class=&quot;base-MuiButton-label&quot;]</value>
      <webElementGuid>166125a4-e426-4f2f-90d9-97cc1d70dd5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div/div/div/div/nav/div[2]/div/button[2]/span</value>
      <webElementGuid>ea3c851e-80a9-43f4-8fd6-7b0c29644876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[1]/following::span[2]</value>
      <webElementGuid>44d20c66-a5c2-4f40-b97c-5dc711debc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You have 1 Delayed Inbound Job'])[1]/following::span[9]</value>
      <webElementGuid>aeab3389-fd06-43ed-a675-bc1d17bb7bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounting'])[1]/preceding::span[4]</value>
      <webElementGuid>4c5ff9b2-515f-444d-af54-9b44e7ec5076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button[2]/span</value>
      <webElementGuid>808001cb-314d-4237-99b5-68722708027c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logistics' or . = 'Logistics')]</value>
      <webElementGuid>decc50a7-4db7-4ae6-90db-d6000f3891cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
