<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please input related basic information_buyer</name>
   <tag></tag>
   <elementGuidId>5c098bd6-187e-4032-8ba6-67985c6fd1d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='buyer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;buyer&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>893e2704-9c6e-4858-bff7-c669e77f402b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buyer</value>
      <webElementGuid>ca25a171-a5e8-41a3-aa15-8fb253c70940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15460d90-f189-4575-86d9-471d9eb6c168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>ef049adb-3938-4463-a206-9345bdc051df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SG-TTAP</value>
      <webElementGuid>b3794d49-9d95-468e-a76e-69249e28600a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OSS011_Section_1&quot;)/div[@class=&quot;lcbm-MuiCollapse-root lcbm-MuiCollapse-entered&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapper&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapperInner&quot;]/div[@class=&quot;lcbm-lcbm53&quot;]/form[@class=&quot;lcbm-lcbm537 lcbm-lcbm576&quot;]/div[@class=&quot;lcbm-lcbm539 lcbm-lcbm582&quot;]/div[@class=&quot;lcbm-lcbm541&quot;]/div[@class=&quot;lcbm-lcbm548&quot;]/div[@class=&quot;lcbm-lcbm554 lcbm-lcbm559&quot;]/div[@class=&quot;lcbm-lcbm543&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>29c62ab5-37bf-4769-9eb3-75f59992206a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='buyer']</value>
      <webElementGuid>79bacbe7-065d-4ebf-9727-0d2c2392f412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='OSS011_Section_1']/div[2]/div/div/div/form/div[6]/div/div[2]/div/div/div/input</value>
      <webElementGuid>965671ec-4eec-4e45-a386-ec752e8d94a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/div/div/div/input</value>
      <webElementGuid>a4cc8616-1d44-4311-b953-7abe97631b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'buyer' and @type = 'text']</value>
      <webElementGuid>3c97ca0f-7860-4108-90b2-8cdb2b55de75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
