<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Basic info (order summary)_lcbm-MuiButtonBase-root lcbm-MuiIconButton-root</name>
   <tag></tag>
   <elementGuidId>62c82df1-b8b3-48b5-a493-38576c338d89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ONS011_Section_4']/div/div[3]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ONS011_Section_4 > div.lcbm-lcbm152 > div.lcbm-lcbm163 > button.lcbm-MuiButtonBase-root.lcbm-MuiIconButton-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19c6bb5a-8686-4f05-9492-564d636c8e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiButtonBase-root lcbm-MuiIconButton-root</value>
      <webElementGuid>7e0331b8-7619-4e30-b2f7-9133d9666336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f8df17d-6e2a-477b-bd32-a90abb4ae660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29adeb68-e1b2-4643-aaf1-7eba3dbde411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ONS011_Section_4&quot;)/div[@class=&quot;lcbm-lcbm152&quot;]/div[@class=&quot;lcbm-lcbm163&quot;]/button[@class=&quot;lcbm-MuiButtonBase-root lcbm-MuiIconButton-root&quot;]</value>
      <webElementGuid>6a6a7d7d-984a-4853-8667-11bd5f5d8a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[42]</value>
      <webElementGuid>5ca42cca-25ba-41db-bcf7-49d5724da6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ONS011_Section_4']/div/div[3]/button</value>
      <webElementGuid>30691b5f-42d6-41bf-bc71-08bf5f273f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic info (order summary)'])[1]/following::button[1]</value>
      <webElementGuid>5e9f9fbf-f3fc-4a27-af65-fd64b8dc0ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AND'])[2]/following::button[12]</value>
      <webElementGuid>846efe8b-324f-477f-96a8-2bb0e0f3d342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order'])[1]/preceding::button[2]</value>
      <webElementGuid>0a4e973e-1d68-4369-ae14-b0de0dbe82f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logistics'])[1]/preceding::button[3]</value>
      <webElementGuid>1fb973a5-220e-4cb6-bad1-aa63b865d156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[3]/button</value>
      <webElementGuid>5414b59f-3044-438d-957a-c513ac98718c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>a4ad7772-bb45-4d19-b157-08574789a8ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
