<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Basic info (order summary)_orderRefNo</name>
   <tag></tag>
   <elementGuidId>499651e9-b6f1-49b1-8114-78b36a520acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='orderRefNo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;orderRefNo&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c0c93b6d-0361-43e9-a5a9-40d1acc62627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>orderRefNo</value>
      <webElementGuid>e2346b57-e40f-4deb-8700-5f77fff8aaeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c61d424-f9c1-4a00-bdb1-f8a7cd80e3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lcbm-MuiInputBase-input lcbm-MuiInput-input</value>
      <webElementGuid>8e05d1d2-77ca-432e-9ae8-1c474c5cb17f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ONS011_Section_4&quot;)/div[@class=&quot;lcbm-MuiCollapse-root lcbm-MuiCollapse-entered&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapper&quot;]/div[@class=&quot;lcbm-MuiCollapse-wrapperInner&quot;]/div[@class=&quot;lcbm-lcbm113&quot;]/form[@class=&quot;lcbm-lcbm168 lcbm-lcbm231&quot;]/div[@class=&quot;lcbm-lcbm170 lcbm-lcbm232&quot;]/div[@class=&quot;lcbm-lcbm181&quot;]/div[@class=&quot;lcbm-lcbm188&quot;]/div[@class=&quot;lcbm-lcbm194&quot;]/div[@class=&quot;lcbm-lcbm183&quot;]/div[@class=&quot;lcbm-MuiInputBase-root lcbm-MuiInput-root Mui-focused Mui-focused&quot;]/input[@class=&quot;lcbm-MuiInputBase-input lcbm-MuiInput-input&quot;]</value>
      <webElementGuid>b7ffa860-a6ab-4318-b904-0b9637664469</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='orderRefNo']</value>
      <webElementGuid>d4413aa0-944c-4f4d-af6e-2eb907de2546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ONS011_Section_4']/div[2]/div/div/div/form/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>7b3691f7-03fb-419e-ba45-7bfc78bf048a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>4786ff66-4e35-4018-88d0-d933ea5fb3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'orderRefNo' and @type = 'text']</value>
      <webElementGuid>765e5e9a-4af4-431d-8d78-dfb99be4f393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
