<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_company</name>
   <tag></tag>
   <elementGuidId>047d298a-0073-4c52-bfbe-b853f3d672a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.base-MuiButtonBase-root.base-MuiIconButton-root.base-MuiAutocomplete-popupIndicator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@title='Open']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>81c8e63b-a4bc-482b-862a-9b4a70b7e106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiButtonBase-root base-MuiIconButton-root base-MuiAutocomplete-popupIndicator</value>
      <webElementGuid>8be13296-989a-4c35-8613-f2dd1c3845b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>25f277d5-60bd-477f-b5a0-51c57f87f3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed67d6a8-a6d8-4ea9-a0c0-b8c0c94a92e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>7d8f9338-75ef-4e12-b7dd-67aa0a62c2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Open</value>
      <webElementGuid>9ba1c110-5d1b-4d38-9010-ba8c207dd56a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;base-base85&quot;]/div[@class=&quot;base-MuiPaper-root base-base86 base-MuiPaper-elevation1 base-MuiPaper-rounded&quot;]/ul[@class=&quot;base-MuiList-root base-base87 base-MuiList-padding&quot;]/li[@class=&quot;base-MuiListItem-root base-base89 base-MuiListItem-gutters&quot;]/div[@class=&quot;base-MuiAutocomplete-root base-MuiAutocomplete-fullWidth base-MuiAutocomplete-hasPopupIcon&quot;]/div[@class=&quot;base-MuiInputBase-root base-base90 base-MuiInputBase-fullWidth base-MuiInputBase-adornedEnd&quot;]/div[@class=&quot;base-MuiAutocomplete-endAdornment&quot;]/button[@class=&quot;base-MuiButtonBase-root base-MuiIconButton-root base-MuiAutocomplete-popupIndicator&quot;]</value>
      <webElementGuid>2c48fb83-6076-4ec3-b29f-0d8cedaf1433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[70]</value>
      <webElementGuid>7319dd4b-fd64-4773-927b-8f52c97d9fc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::button[1]</value>
      <webElementGuid>b53f8101-ff5a-43b6-9aba-4a881b4d61a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::button[1]</value>
      <webElementGuid>89217bc0-7c73-4b30-b2fd-aab23846ca02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Setting'])[1]/preceding::button[1]</value>
      <webElementGuid>75f531b1-020c-4b1e-a4ab-f24858532a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/preceding::button[1]</value>
      <webElementGuid>18846795-f7d4-408f-9270-47bef6a90861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/button</value>
      <webElementGuid>e37432fd-d12f-4e77-9ba9-d940a903f510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @title = 'Open']</value>
      <webElementGuid>c311093c-e23f-4a1b-a431-9c4a8197eb5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
