<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_aazwanSGDC-Azwan</name>
   <tag></tag>
   <elementGuidId>de463e8b-2ace-4de7-b865-0554bcdff313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[id='webapp-base'] p:nth-child(2)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and (text() = 'aazwanSGDC-Azwan' or . = 'aazwanSGDC-Azwan')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='webapp-base']/div/div/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d4d724d4-c700-45ae-ae12-1d78f625fa06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base-MuiButtonBase-root base-MuiButton-root base-base63 base-MuiButton-text base-base65</value>
      <webElementGuid>acabb568-ce4a-4c16-9d21-ed8f9335fed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6c2f0dae-9773-4c0c-836a-2053ff7ddc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97c4e009-1022-4fb3-b3a4-238cfab2e4ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>aazwanSGDC-Azwan</value>
      <webElementGuid>7aa58e88-2bdf-47a6-9019-041e69b9731d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;webapp-base&quot;)/div[@class=&quot;base-base42&quot;]/div[@class=&quot;base-base43&quot;]/div[@class=&quot;base-base44&quot;]/div[@class=&quot;base-base47&quot;]/button[@class=&quot;base-MuiButtonBase-root base-MuiButton-root base-base63 base-MuiButton-text base-base65&quot;]</value>
      <webElementGuid>2746aba9-fb19-4277-9c4c-984288569bd7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[67]</value>
      <webElementGuid>c6bebd57-ee93-42f9-8f45-2ee2c649e6d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='webapp-base']/div/div/div/div[2]/button</value>
      <webElementGuid>42eb5ef9-b8a3-4602-94f6-ba0b18d2401f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privilege'])[1]/following::button[2]</value>
      <webElementGuid>2a785026-3082-46e1-ab67-4c733c41e02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master'])[1]/following::button[3]</value>
      <webElementGuid>4d41d64a-513a-4d98-899d-a381702f7142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chats'])[1]/preceding::button[2]</value>
      <webElementGuid>853f24f1-6d31-4bcf-abba-f32e63180abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8994f061-191c-4faf-8eb2-162eb4e98cc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'aazwanSGDC-Azwan' or . = 'aazwanSGDC-Azwan')]</value>
      <webElementGuid>634c06f4-2f9f-4d32-ad6d-de21070a39e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
