<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_closeModel</name>
   <tag></tag>
   <elementGuidId>5aefb793-ca19-45c7-b02e-3c409f7dcaa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#closeModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='closeModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8653babc-487a-439f-9897-5acdab106f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>ec8658b9-0169-4dc0-8e3c-24c747cc0eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>closeModel</value>
      <webElementGuid>24087dda-e1a9-4b2b-a451-a4c8556a69a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>26a7f2d7-3643-4199-a706-cd05efd8db20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;closeModel&quot;)</value>
      <webElementGuid>3e622784-b5e4-4d20-96bc-1e902f95b280</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='closeModel']</value>
      <webElementGuid>b40b1206-6a3f-47c1-92fc-343e8009f821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/span</value>
      <webElementGuid>5809ea50-859e-4b2a-b57c-1bcaa4bc1287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECOMMENDATIONS'])[4]/following::span[1]</value>
      <webElementGuid>f5cee539-5ae2-4c19-80d0-44264488fe06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::span[1]</value>
      <webElementGuid>8b205adf-cdf0-4317-8997-23b08d0937e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='What can you do in SO Monitoring?'])[1]/preceding::span[1]</value>
      <webElementGuid>7bfdca7f-28d1-4c8d-863b-7c786c92d417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='‹'])[1]/preceding::span[1]</value>
      <webElementGuid>fc216767-70f3-4df6-be1d-d92ec8aefcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/span</value>
      <webElementGuid>dca6bfac-fe8b-4b89-a7bb-456f33a1cfc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'closeModel' and (text() = '×' or . = '×')]</value>
      <webElementGuid>681e09aa-a32a-4b91-8f17-720199c42da3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
